filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /opt/javalogs/exercise/*.log
  tags: ["java-app"]
  multiline:
    negate: true
    match: after
    max_lines: 1000
    timeout: 30s

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_cloud_metadata: ~


output:
  # elasticsearch:
  #   hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  #   username: '${ELASTICSEARCH_USERNAME:}'
  #   password: '${ELASTICSEARCH_PASSWORD:}'

  logstash:
    hosts: ["logstash:5044"]


#============================== Kibana =========================================
setup.kibana:
  host: "kibana:5601"